export const ADD_ORDER_PENDING = "ADD_ORDER_PENDING";
export const ADD_ORDER_SUCCESS = "ADD_ORDER_SUCCESS";
export const ADD_ORDER_FAILED = "ADD_ORDER_FAILED";

export const REQUEST_ORDERS_PENDING = "REQUEST_ORDERS_PENDING";
export const REQUEST_ORDERS_SUCCESS = "REQUEST_ORDERS_SUCCESS";
export const REQUEST_ORDERS_FAILED = "REQUEST_ORDERS_FAILED";
