export const ACCOUNT_DEPOSIT_SUCCESS = "ACCOUNT_DEPOSIT_SUCCESS";
export const ACCOUNT_DEPOSIT_FAILED = "ACCOUNT_DEPOSIT_FAILED";

export const ACCOUNT_WITHDRAWAL_SUCCESS = "ACCOUNT_WITHDRAWAL_SUCCESS";
export const ACCOUNT_WITHDRAWAL_FAILED = "ACCOUNT_WITHDRAWAL_FAILED";
