export const CREATE_EVENT_FAILED = "CREATE_EVENT_FAILED";
export const CREATE_EVENT_SUCCESS = "CREATE_EVENT_SUCCESS";

export const ACTIVATE_EVENT = "ACTIVATE_EVENT";
export const DEACTIVATE_EVENT = "DEACTIVATE_EVENT";

export const DELETE_EVENT_SUCCESS = "DELETE_EVENT_SUCCESS";
export const DELETE_EVENT_FAILED = "DELETE_EVENT_FAILED";

export const GET_EVENT_PENDING = "GET_EVENT_PENDING";
export const GET_EVENT_SUCCESS = "GET_EVENT_SUCCESS";
export const GET_EVENT_FAILED = "GET_EVENT_FAILED";
