export const ACCOUNT_DEPOSIT_PENDING = "ACCOUNT_DEPOSIT_PENDING";
export const ACCOUNT_DEPOSIT_SUCCESS = "ACCOUNT_DEPOSIT_SUCCESS";
export const ACCOUNT_DEPOSIT_FAILED = "ACCOUNT_DEPOSIT_FAILED";

export const ACCOUNT_WITHDRAWAL_PENDING = "ACCOUNT_WITHDRAWAL_PENDING";
export const ACCOUNT_WITHDRAWAL_SUCCESS = "ACCOUNT_WITHDRAWAL_SUCCESS";
export const ACCOUNT_WITHDRAWAL_FAILED = "ACCOUNT_WITHDRAWAL_FAILED";

export const GET_TRANSACTIONS = "GET_TRANSACTIONS";

export const GET_ACCOUNT_DETAILS = "GET_ACCOUNT_DETAILS";
