export const GET_OWNED_STOCKS_PENDING = "GET_OWNED_STOCKS_PENDING";
export const GET_OWNED_STOCKS_SUCCESS = "GET_OWNED_STOCKS_SUCCESS";
export const GET_OWNED_STOCKS_FAILED = "GET_OWNED_STOCKS_FAILED";
