export const SET_SELECTED_INDEX = "SET_SELECTED_INDEX";

export const ADD_WATCHLIST_PENDING = "ADD_WATCHLIST_PENDING";
export const ADD_WATCHLIST_SUCCESS = "ADD_WATCHLIST_SUCCESS";
export const ADD_WATCHLIST_FAILED = "ADD_WATCHLIST_FAILED";

export const ADD_SYMBOL_PENDING = "ADD_SYMBOL_PENDING";
export const ADD_SYMBOL_SUCCESS = "ADD_SYMBOL_SUCCESS";
export const ADD_SYMBOL_FAILED = "ADD_SYMBOL_FAILED";

export const DELETE_WATCHLIST_PENDING = "DELETE_WATCHLIST_PENDING";
export const DELETE_WATCHLIST_SUCCESS = "DELETE_WATCHLIST_SUCCESS";
export const DELETE_WATCHLIST_FAILED = "DELETE_WATCHLIST_FAILED";

export const REMOVE_SYMBOL_PENDING = "REMOVE_SYMBOL_PENDING";
export const REMOVE_SYMBOL_SUCCESS = "REMOVE_SYMBOL_SUCCESS";
export const REMOVE_SYMBOL_FAILED = "REMOVE_SYMBOL_FAILED";

export const GET_WATCHLIST_PENDING = "GET_WATCHLIST_PENDING";
export const GET_WATCHLIST_SUCCESS = "GET_WATCHLIST_SUCCESS";
export const GET_WATCHLIST_FAILED = "GET_WATCHLIST_FAILED";
