export const USER_DATA_PENDING = "USER_DATA_PENDING";
export const USER_DATA_SUCCESS = "USER_DATA_SUCCESS";
export const USER_DATA_FAILED = "USER_DATA_FAILED";

export const DELETE_USER_DATA = "DELETE_USER_DATA";
